[metadata]
name = mpm
version = 0.1.0
authors = Bryan Runck
author_email = runck014@umn.edu
description = Minimum Plant Model (MPM) - A modular framework for simulating plant growth
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/DRWang3/MPM_testing
project_urls =
    Bug Tracker = https://github.com/DRWang3/MPM_testing/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering

[options]
package_dir =
    = .
packages = find:
python_requires = >=3.7
install_requires =
    numpy
    pandas
    matplotlib

[options.packages.find]
where = .
